name: starter

channels:
  - defaults
  - conda-forge
  
dependencies:
  - python=3.7
  - ipython
  - sphinx
  - sphinx_rtd_theme
  - pandas
  - pytest
  - pip
  - pip:
    - -r requirements_pip_only.txt